#! /bin/sh

# Prompt for GitHub token if not set
if [ -z "$GITHUB_TOKEN" ]; then
    echo "Please enter your GitHub Personal Access Token:"
    read -r GITHUB_TOKEN
fi

repoName=$1
while [ -z "$repoName" ]
do
    echo 'Provide a repository name'
    read -r -p $'Repository name:' repoName
done

echo "# $repoName" >> README.md
git init
git add .
git commit -m "First commit"

# Use the token securely
curl -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/user/repos -d '{"name": "'"$repoName"'", "private":false}'

GIT_URL=$(curl -H "Authorization: token $GITHUB_TOKEN" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/Dhruvar27/"$repoName" | jq -r '.clone_url')

git branch -M main
git remote add origin "$GIT_URL"
git push -u origin main

